# Generated by Django 3.1.2 on 2020-10-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('conteudo', models.TextField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberarea.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberarea.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='aulas',
            field=models.ManyToManyField(through='memberarea.Sequencia', to='memberarea.Aula'),
        ),
    ]
